# Generated by Django 5.2.17 on 2026-09-30 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('tz', models.CharField(help_text='IANA 时区，如 Asia/Shanghai', max_length=40)),
            ],
            options={
                'db_table': 'airport',
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=2)),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('rbd', models.CharField(max_length=1, verbose_name='订座舱位 RBD')),
                ('fare_code', models.CharField(max_length=12)),
                ('direction', models.CharField(choices=[('OW', 'One way 单程'), ('RT', 'Round trip 来回程')], max_length=2)),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fare',
                'ordering': ['carrier', 'origin', 'destination', 'rbd'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=6, unique=True)),
                ('passenger', models.CharField(max_length=32)),
                ('issued_at', models.DateTimeField()),
                ('fare_snapshot', models.JSONField(default=dict)),
                ('base_amount_cny', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount_cny', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cny', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='TaxDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('cabin_name', models.CharField(max_length=16)),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tax_definition',
            },
        ),
        migrations.CreateModel(
            name='FareRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_versions', to='pricing.fare')),
            ],
            options={
                'db_table': 'fare_rule_version',
                'ordering': ['fare_id', '-version'],
                'unique_together': {('fare', 'version')},
            },
        ),
        migrations.AddField(
            model_name='fare',
            name='current_rule_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_fares', to='pricing.fareruleversion'),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=5)),
                ('dep_utc', models.DateTimeField()),
                ('arr_utc', models.DateTimeField()),
                ('arr_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='pricing.airport')),
                ('dep_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='pricing.airport')),
            ],
            options={
                'db_table': 'flight',
                'ordering': ['dep_utc', 'carrier', 'number'],
                'unique_together': {('carrier', 'number', 'dep_utc')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ELIGIBILITY', '适用舱位/航司/航段'), ('STOPOVERS', '停留次数限制'), ('TRANSFERS', '转机次数限制'), ('MIN_STAY', '最短停留（当地日历日）'), ('MAX_STAY', '最长停留（当地日历日）'), ('COMBINABILITY', '联程/运价组合限制'), ('CHANGE_FEE', '改签手续费（命中即生效）'), ('CUSTOM', '自定义表达式')], max_length=16)),
                ('description', models.CharField(max_length=200)),
                ('expression', models.TextField(help_text='受限布尔/数值表达式，例如 min_stay_days >= 3')),
                ('fee_cny', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.fareruleversion')),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='CabinInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbd', models.CharField(max_length=1)),
                ('cabin_name', models.CharField(max_length=16)),
                ('seats', models.PositiveIntegerField(default=0)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabins', to='pricing.flight')),
            ],
            options={
                'verbose_name_plural': 'cabin inventories',
                'db_table': 'cabin_inventory',
                'unique_together': {('flight', 'rbd')},
            },
        ),
        migrations.CreateModel(
            name='TicketCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField()),
                ('rbd', models.CharField(max_length=1)),
                ('status', models.CharField(choices=[('OPEN', '未使用'), ('USED', '已乘机'), ('EXCHANGED', '已换开'), ('REFUNDED', '已退')], default='OPEN', max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.flight')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='pricing.order')),
            ],
            options={
                'db_table': 'ticket_coupon',
                'ordering': ['order_id', 'seq'],
                'unique_together': {('order', 'seq')},
            },
        ),
    ]
