# Generated by Django 5.2.17 on 2026-09-30 06:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=48, verbose_name='IANA 时区')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('PRICE', '新建行程试算'), ('CHANGE', '改签试算')], default='PRICE', max_length=8)),
                ('scenario', models.CharField(blank=True, max_length=32, verbose_name='教学场景标签')),
                ('status', models.CharField(choices=[('OK', '试算成功'), ('FAILED', '无可用组合')], max_length=8)),
                ('request_payload', models.JSONField(default=dict)),
                ('base_fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('published_at', models.DateTimeField()),
                ('effective_from', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('FIXED_PER_COMPONENT', '每运价组件固定额'), ('FIXED_PER_SEGMENT', '每航段固定额'), ('PERCENT_OF_BASE', '按运价基数百分比')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_code', models.CharField(max_length=24)),
                ('fare_type', models.CharField(choices=[('OW', '单程'), ('RT', '往返')], default='OW', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运价金额（不含税）')),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('booking_classes', models.JSONField(default=list, verbose_name='适用预订舱位')),
                ('end_on_end_allowed', models.BooleanField(default=False, verbose_name='允许与其他运价联程组合')),
                ('advance_purchase_days', models.IntegerField(default=0, verbose_name='提前购票天数')),
                ('change_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='改签手续费')),
                ('active', models.BooleanField(default=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares', to='pricing.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares_to', to='pricing.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares_from', to='pricing.airport')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares', to='pricing.ruleversion')),
            ],
            options={
                'unique_together': {('rule_version', 'fare_code')},
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=6)),
                ('dep_utc', models.DateTimeField(verbose_name='UTC 起飞时刻')),
                ('arr_utc', models.DateTimeField(verbose_name='UTC 到达时刻')),
                ('arr_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='pricing.airport')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='pricing.airline')),
                ('dep_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='pricing.airport')),
            ],
            options={
                'ordering': ['dep_utc'],
                'unique_together': {('carrier', 'flight_no', 'dep_utc')},
            },
        ),
        migrations.CreateModel(
            name='QuoteComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('segment_indexes', models.JSONField(default=list)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.fare')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pricing.quote')),
            ],
        ),
        migrations.CreateModel(
            name='RuleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_seq', models.IntegerField(null=True)),
                ('segment_indexes', models.JSONField(default=list)),
                ('fare_code', models.CharField(blank=True, max_length=24)),
                ('partition_key', models.CharField(max_length=64, verbose_name='组合切分方式')),
                ('rule_code', models.CharField(max_length=24)),
                ('rule_category', models.CharField(blank=True, max_length=16)),
                ('result', models.CharField(choices=[('PASS', '通过'), ('FAIL', '未通过'), ('INFO', '说明')], max_length=8)),
                ('message', models.CharField(max_length=255)),
                ('expression', models.TextField(blank=True)),
                ('context', models.JSONField(default=dict)),
                ('rule_version', models.CharField(blank=True, max_length=32)),
                ('chosen', models.BooleanField(default=False, verbose_name='是否中选组合')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='pricing.quote')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='rule_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='pricing.ruleversion'),
        ),
        migrations.CreateModel(
            name='QuoteTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_seq', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='pricing.quote')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.taxrule')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=16, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ISSUED', '已出票(培训)'), ('EXCHANGED', '已改签(培训)'), ('VOID', '作废(培训)')], default='ISSUED', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='pricing.quote')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OK', '可改签'), ('BLOCKED', '不可改签'), ('COMMITTED', '已换开(培训记录)')], max_length=10)),
                ('coupon_check', models.JSONField(default=list, verbose_name='票联状态检查明细')),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fare_diff', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='价差（正补收/负退还，均为模拟）')),
                ('change_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('collect_or_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('new_quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.quote')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='pricing.trainingticket')),
            ],
        ),
        migrations.CreateModel(
            name='FareRouteLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.airport')),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_legs', to='pricing.fare')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.airport')),
            ],
            options={
                'ordering': ['fare', 'seq'],
                'unique_together': {('fare', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='CabinInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_class', models.CharField(max_length=2, verbose_name='预订舱位')),
                ('cabin', models.CharField(default='经济舱', max_length=16, verbose_name='物理舱位')),
                ('seats', models.IntegerField(default=0, verbose_name='剩余座位')),
                ('status', models.CharField(choices=[('OPEN', '可售'), ('CLOSED', '关闭'), ('WAITLIST', '候补')], default='OPEN', max_length=8)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabins', to='pricing.flight')),
            ],
            options={
                'unique_together': {('flight', 'booking_class')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24)),
                ('category', models.CharField(choices=[('TRANSFER', '转机'), ('STOPOVER', '停留'), ('MIN_STAY', '最短停留'), ('MAX_STAY', '最长停留'), ('COMBINATION', '联程组合'), ('BOOKING_CLASS', '舱位'), ('ADVANCE', '提前购票'), ('DATE_CHANGE', '跨日期变更'), ('AVAILABILITY', '舱位可用性'), ('ITINERARY', '行程顺序')], max_length=16)),
                ('expression', models.TextField()),
                ('message_zh', models.CharField(max_length=255)),
                ('hardcoded', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('INTERNAL', '组件内部'), ('BOUNDARY', '组件间衔接'), ('BOTH', '内部与衔接')], default='INTERNAL', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.fare')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='pricing.ruleversion')),
            ],
            options={
                'ordering': ['fare', 'code'],
                'unique_together': {('fare', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('booking_class', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('OPEN', '未使用'), ('USED', '已使用'), ('EXCHANGED', '已换开')], default='OPEN', max_length=10)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.fare')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pricing.flight')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='pricing.trainingticket')),
            ],
            options={
                'ordering': ['ticket', 'seq'],
                'unique_together': {('ticket', 'seq')},
            },
        ),
    ]
